import CursorFollower from "@/components/cursor-follower";
import AdaptiveHeader from "@/components/sections/adaptive-header";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { ttcommons } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ttcommons.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AdaptiveHeader />
          {children}
          <CursorFollower />
        </ThemeProvider>
      </body>
    </html>
  );
}
